/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucle_7;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        int select;
        String pass = "0000";
        String passin;
        
        do{
            
            System.out.println("1. Asignar nueva combinación");
            System.out.println("2. Abir caja fuerte");
            System.out.println("0. Salir");
            
            System.out.println("Seleccione una opción: ");
            select = miScan.nextInt();
        
            if(select == 1){
                
                System.out.println("Introduzca la contraseña: ");
                passin = miScan.next();
                
                if(passin.equals(pass)){
                    
                    System.out.println("Introduzca una nueva contraseña: ");
                    passin = miScan.next();
                    
                    if(passin.length() != 4){
                        System.out.println("La contraseña debe ser de 4 caracteres");
                    }
                    else{   
                        pass = passin;
                        System.out.println("Combinación almacenada");
                    }
                }
                else{
  
                    System.out.println("Combinación errónea");
                }
            }
            else if(select == 2){
                
                System.out.println("Introduzca la contraseña: ");
                passin = miScan.next();
                
                if(passin.equals(pass)){
                    
                    System.out.println("Caja fuerte abierta");
  
                }
                else{
                    
                    System.out.println("Combinación errónea");
                }
            }
            else if(select != 0){
                
                System.out.println("Esa opción no es correcta");
            }
        }while(select != 0);
    }
}
